### ISSUE TITLE
VS Code port calculation completion

### ISSUE THREAD

**Issue by voldikss** [weirongxu/coc-calc#13]
dalao, would you consider porting this coc.nvim extension to VS Code extension?

**Comment by weirongxu** [comment]
Good idea, Maybe I should separate `calc-parser` into a submodule.
But I need to wait a few days to have time to do this.

**Comment by voldikss** [comment]
> But I need to wait a few days to have time to do this.
It's totally fine~

**Comment by weirongxu** [comment]
Released:
https://marketplace.visualstudio.com/items?itemName=raidou.calc
