### ISSUE TITLE
Sum column of numbers

### ISSUE THREAD

**Issue by borisbrodski** [weirongxu/coc-calc#16]
I'm not sure, if this feature would be in the scope of this plugin, but :)

It would be great to be able to sum (mean, ...) numbers in a column

Example: Suppose I have following ascii table

```
    #     | size
    ------+------
    1     | 223
    2     | 1
    3     | 21
    ------+------
    total |
```

Now visual-block-selecting the "size" column I would like to put the sum into the "-register.

Detecting column of numbers without visual-block selection would be cool, but only nice to have, IMO.

Another way of specifying numbers: matching it with the regexp search pattern, like

`/| *[0-9]\+/
`

**Comment by weirongxu** [comment]
I'll add an API, let user manually execute their own expression.

Example:

```vim
function s:sum_selected()
  y
  CocAction('runCommand', 'calc.calculate', join(split(getreg('"'), '\u\s|\n'), '+'))
endfunction
```

**Comment by weirongxu** [comment]
I suggest using plugins like https://github.com/coderifous/textobj-word-column.vim for block selection and then handle it by yourself
