### ISSUE TITLE
Error: Cannot find module './calc-parser'

### ISSUE THREAD

**Issue by derekstavis** [weirongxu/coc-calc#2]
Thanks for putting this together. This will be a perfect replacement for Soulver.

I couldn't make it work though, I receive this error when starting CoC:

```
/Users/derekstavis/.config/coc/extensions/node_modules/coc-calc/lib/index.js: Error: Cannot find module './calc-parser'
```

**Comment by weirongxu** [comment]
Thank you for pointing out this issue, latest release should fixed this.

**Comment by derekstavis** [comment]
working perfectly now! thanks!
